FROM tomcat:10.1-jdk21-temurin

# Clean default apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy the WAR file generated by Gradle (it's created by the pipeline beforehand)
COPY build/libs/*.war /usr/local/tomcat/webapps/app.war

EXPOSE 8080
CMD ["catalina.sh", "run"]