FROM tomcat:10.1-jdk17

# Clean default apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy the war file generated by Gradle (it's created by the pipeline beforehand)
COPY build/libs/*.war /usr/local/tomcat/webapps/app.war

EXPOSE 8080
CMD ["catalina.sh", "run"]